name: ci/docker image build and publish 

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          push: true
          tags: kstsai/pytester3:latest
